name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
      - name: Install Tools
        run: |
          pip install flet-cli yfinance pandas-ta
      - name: Build APK
        run: |
          # بما أن الملفات بالخارج، نستخدم النقطة . فقط
          flet build apk .
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlSafi-Pro-App
          path: build/apk/*.apk
