name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: Install Dependencies
        run: |
          pip install flet-cli yfinance pandas-ta

      - name: Build Android APK
        run: |
          # حذفنا الأمر المسبب للخطأ وتركنا الأمر الأساسي فقط للبناء
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlSafi-Pro-App
          # هذا المسار سيبحث عن ملف الـ APK في أي مكان نتج فيه
          path: "**/build/apk/*.apk"
